import com.example.fanwenhao.drools.Message
import java.util.concurrent.atomic.AtomicInteger;
import com.example.fanwenhao.drools.Result
import java.text.DateFormat
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date;

global String temp;
global AtomicInteger count;


//函数示例
function void print(String messgae){
    System.out.println(messgae);
}


//规则1
rule "say-hi"
    agenda-group "group1"
    when
        $m: Message(target!=null)
    then
        print("：：：：：：：：：：：：：：：：：：");
        insert( new Result("1","123s"));
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        System.out.println(df.format(new Date()));
        Calendar cal = Calendar.getInstance();
        insert(new Date());
        cal.setTime(new Date());
        cal.add(Calendar.HOUR, 5);
        System.out.println(df.format(cal.getTime()));
    end

//规则2
rule "say"
    agenda-group "group2"
    when
        $m: Message(target!=null)
    then
        print("++++++++++++++++++++");
        insert( new Result("1","123s"));
    end
